# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mult_ <- function(X, Y) {
    .Call(`_HOFS_mult_`, X, Y)
}

array_mult <- function(X, Y) {
    .Call(`_HOFS_array_mult`, X, Y)
}

Reduce_cpp <- function(x) {
    .Call(`_HOFS_Reduce_cpp`, x)
}

